version: 1.0.{build}
install:
  - git submodule update --init --recursive
  - nuget restore
  - pushd gta5-extended-video-export
  - appveyor DownloadFile https://www.dev-c.com/gtav/scripthookv/scripthookv_sdk.zip -FileName sdk.zip
  - 7z x sdk.zip -osdk
  - popd
platform: x64
configuration: Release
build:
  project: gta5-extended-video-export.sln
  verbosity: detailed
after_build:
  - pushd x64\Release
  - mkdir EVE\dlls
  - ps: Move-Item -Path ".\YourProject.dll" -Destination ".\YourProject.asi"
  - ps: Move-Item -Path ".\YourProject.asi" -Destination .\EVE\dlls
  - dir /s /b *.asi EVE
  - 7z a -r ..\..\ExtendedVideoExport-git-%APPVEYOR_BUILD_VERSION%.zip *.asi EVE
test: off
artifacts:
  - path: ExtendedVideoExport-git-$(APPVEYOR_BUILD_VERSION).zip
