version: 1.0.{build}
install:
  - git submodule update --init --recursive
  - nuget restore
  - pushd gta5-extended-video-export
  - ps: |
      # Download the ScriptHookV SDK
      $sdkUrl = 'https://www.dev-c.com/gtav/scripthookv/scripthookv_sdk.zip'
      $outputFile = 'sdk.zip'
      Invoke-WebRequest -Uri $sdkUrl -OutFile $outputFile -UseBasicParsing
      
      # Check if the downloaded file is a valid ZIP archive
      if ((Get-Item $outputFile).Length -lt 100KB) {
          Write-Error "Downloaded file is too small. It may not be the SDK."
          Get-Content $outputFile | Select-Object -First 20
          exit 1
      }
  - 7z x sdk.zip -osdk
  - popd
platform: x64
configuration: Release
build:
  project: gta5-extended-video-export.sln
  verbosity: detailed
after_build:
  - pushd x64\Release
  - mkdir EVE\dlls
  - ps: Move-Item -Path ".\YourProject.dll" -Destination ".\YourProject.asi"
  - ps: Move-Item -Path ".\YourProject.asi" -Destination .\EVE\dlls
  - dir /s /b *.asi EVE
  - 7z a -r ..\..\ExtendedVideoExport-git-%APPVEYOR_BUILD_VERSION%.zip *.asi EVE
test: off
artifacts:
  - path: ExtendedVideoExport-git-$(APPVEYOR_BUILD_VERSION).zip
