version: 1.0.{build}
install:
  - git submodule update --init --recursive
  - nuget restore
  - pushd gta5-extended-video-export
  - ps: |
      $sdkUrl = 'http://www.dev-c.com/gtav/scripthookv/scripthookv_sdk.zip'
      $outputFile = 'sdk.zip'
      $headers = @{
          'User-Agent' = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'
          'Accept' = '*/*'
          'Referer' = 'http://www.dev-c.com/gtav/scripthookv/'
      }
      Invoke-WebRequest -Uri $sdkUrl -OutFile $outputFile -Headers $headers -UseBasicParsing
      if ((Get-Item $outputFile).Length -lt 500KB) {
          Write-Error "Downloaded file is too small. Download may have failed."
          Write-Host "Contents of $outputFile:"
          Get-Content $outputFile
          exit 1
      }
      # Verify the downloaded file
      function Test-IsZipFile {
          param([string]$FilePath)
          try {
              $zip = [System.IO.Compression.ZipFile]::OpenRead($FilePath)
              $zip.Dispose()
              return $true
          } catch {
              return $false
          }
      }
      if (-not (Test-IsZipFile $outputFile)) {
          Write-Error "Downloaded file is not a valid ZIP archive."
          exit 1
      }
  - 7z x sdk.zip -osdk
  - popd
platform: x64
configuration: Release
build:
  project: gta5-extended-video-export.sln
  verbosity: detailed
after_build:
  - pushd x64\Release
  - mkdir EVE\dlls
  - ps: Move-Item -Path ".\ExtendedVideoExport.dll" -Destination ".\ExtendedVideoExport.asi"
  - ps: Move-Item -Path ".\ExtendedVideoExport.asi" -Destination .\EVE\dlls
  - dir /s /b *.asi EVE
  - 7z a -r ..\..\ExtendedVideoExport-git-%APPVEYOR_BUILD_VERSION%.zip *.asi EVE
test: off
artifacts:
  - path: ExtendedVideoExport-git-$(APPVEYOR_BUILD_VERSION).zip
